<?php
    return array(
        # Ruby
        'ruby'          => 'Ruby',
        'mri'           => 'MRI',
        'rails'         => 'Rails',
        'gem'           => 'Gem',
        'rubygems'      => 'RubyGems',
        'rubyonrails'   => 'Ruby on Rails',
        'ror'           => 'Ruby on Rails',
        'rubyconf'      => 'RubyConf',
        'railsconf'     => 'RailsConf',
        'rubytuesday'   => 'Ruby Tuesday',
    
        'coffeescript'  => 'CoffeeScript',
        'scss'          => 'SCSS',
        'sass'          => 'Sass',
        'railscasts'    => 'RailsCasts',
        'execjs'        => 'ExecJS',
        'cocoapods'     => 'CocoaPods',
        'rack'          => 'Rack',
        'sinatra'       => 'Sinatra',
        'grape'         => 'Grape',
        'unicorn'       => 'Unicorn',
        'capistrano'    => 'Capistrano',
        'puppet'        => 'Puppet',
        'vagrant'       => 'Vagrant',
        'chef'          => 'Chef',
        'passenger'     => 'Passenger',
        
        // 'capybara'      => 'Capybara',
        // 'lotus'         => 'Lotus',
        // 'mina'          => 'Mina',
        // 'rubymotion'    => 'RubyMotion',
        // 'irb'           => 'IRB',
        // 'pry'           => 'Pry',
        // 'jruby'         => 'JRuby',
        // 'mruby'         => 'mRuby',
        // 'rvm'           => 'RVM',
        // 'rbenv'         => 'rbenv',
        // 'yard'          => 'YARD',
        // 'rdoc'          => 'RDoc',
        // 'rspec'         => 'RSpec',
        // 'minitest'      => 'MiniTest',
        // 'thin'          => 'Thin',
        // 'puma'          => 'Puma',
        // 'activerecord'  => 'ActiveRecord',
        // 'active-record' => 'ActiveRecord',
        // 'activemodal'   => 'ActiveModel',
        // 'activesupport' => 'ActiveSupport',
        // 'datamapper'    => 'DataMapper',
        // 'devise'        => 'Devise',
        // 'cancancan'     => 'CanCanCan',
        // 'resque'        => 'Resque',
        // 'sidekiq'       => 'Sidekiq',
        // 'turbolinks'    => 'Turbolinks',
        // 'sprockets'     => 'Sprockets',
        // 'redcarpet'     => 'Redcarpet',
        // 'sunspot'       => 'Sunspot',
        // 'carrierwave'   => 'CarrierWave',
        // 'paperclip'     => 'PaperClip',
        // 'simpleform'    => 'Simple Form',
        // 'kaminari'      => 'Kaminari',
        // 'will_paginate' => 'will_paginate',
        // 'minimagick'    => 'MiniMagick',
        // 'rmagick'       => 'RMagick',
        // 'nokogiri'      => 'Nokogiri',
        // 'god'           => 'God',
        // 'eventmachine'  => 'EventMachine',
        // 'simplecov'     => 'SimpleCov',
        // 'brakeman'      => 'Brakeman',
        // 'activeadmin'   => 'ActiveAdmin',
        // 'railsadmin'    => 'RailsAdmin',
    
        # Python
    
        # Node.js
        'nodejs'        => 'Node.js',
        'npm'           => 'NPM',
    
        # Go
    
        # PHP
        'php'           => 'PHP',
        'pear'          => 'Pear',
        'laravel'       => 'Laravel',
        'laravel4'      => 'Laravel 4',
        'laravel5'      => 'Laravel 5',
        'traits'        => 'Traits',
        'composer'      => 'Composer',
        'homestead'     => 'Homestead',
        'ioc'           => 'IoC',
        'phpspec'       => 'PHPSpec',
        'codeception'   => 'Codeception',
        'thinkphp'      => 'ThinkPHP',
    
        # Cocoa
        'afnetworking'  => 'AFNetworking',
        'reactivecocoa' => 'ReactiveCocoa',
        'three20'       => 'Three20',
    
        # Java
    
        # Programming
        'ssh'           => 'SSH',
        'web'           => 'Web',
        'api'           => 'API',
        'css'           => 'CSS',
        'html'          => 'HTML',
        'json'          => 'JSON',
        'jsonp'         => 'JSONP',
        'xml'           => 'xml',
        'yaml'          => 'YAML',
        'yml'           => 'YAML',
        'ini'           => 'INI',
        'csv'           => 'CSV',
        'soap'          => 'SOAP',
        'ajax'          => 'Ajax',
        'messagepack'   => 'MessagePack',
        'javascript'    => 'JavaScript',
        'js'            => 'JS',
        'png'           => 'PNG',
        'dsl'           => 'DSL',
        'tdd'           => 'TDD',
        'bdd'           => 'BDD',
        'cgi'           => 'CGI',
        'asp.net'       => 'ASP.NET',
        '.net'          => '.NET',
        'rest'          => 'REST',
        'orm'           => 'ORM',
        'oauth'         => 'OAuth',
        'oauth2'        => 'OAuth2',
        'i18n'          => 'I18N',
        'markdown'      => 'Markdown',
    
        # Sites
        'amazon'        => 'Amazon',
        'aws'           => 'AWS',
        'facebook'      => 'Facebook',
        'github'        => 'GitHub',
        'gist'          => 'Gist',
        'ruby_china'    => 'Ruby China',
        'ruby-china'    => 'Ruby China',
        'rubychina'     => 'Ruby China',
        'phphub'        => 'PHPHub',
        'v2ex'          => 'V2EX',
        'hackernews'    => 'Hacker News',
        'heroku'        => 'Heroku',
        'stackoverflow' => 'Stack Overflow',
        'stackexchange' => 'StackExchange',
        'twitter'       => 'Twitter',
        'youtube'       => 'YouTube',
        'slack'         => 'Slack',
        'laracasts'     => 'Laracasts',
    
        # Databases
        'dynamodb'      => 'DynamoDB',
        'mysql'         => 'MySQL',
        'postgresql'    => 'PostgreSQL',
        'sqlite'        => 'SQLite',
        'memcached'     => 'Memcached',
        'mongodb'       => 'MongoDB',
        'redis'         => 'Redis',
        'rethinkdb'     => 'RethinkDB',
        'elasticsearch' => 'Elasticsearch',
        'solr'          => 'Solr',
        'sphinx'        => 'Sphinx',
    
        # System
        'window'        => 'Windows',
        'windows'       => 'Windows',
        'linux'         => 'Linux',
        'mac'           => 'Mac',
        'osx'           => 'OS X',
        'ubuntu'        => 'Ubuntu',
        'rhel'          => 'RHEL',
        'centos'        => 'CentOS',
        'archlinux'     => 'Arch Linux',
        'redhat'        => 'RedHat',
    
        # OpenSource Projects
        'gitlab'        => 'GitLab',
        'gitlabci'      => 'GitLab CI',
        'fontawesome'   => 'Font Awesome',
        'bootstrap'     => 'Bootstrap',
        'less'          => 'Less',
        'jquery'        => 'jQuery',
        'requirejs'     => 'RequireJS',
        'underscore'    => 'Underscore',
        'angularjs'     => 'AngularJS',
        'emberjs'       => 'Ember.js',
        'backbone'      => 'Backbone',
        'seajs'         => 'SeaJS',
        'imagemagick'   => 'ImageMagick',
        'fluentd'       => 'Fluentd',
        'ffmpeg'        => 'FFMPEG',
        'wordpress'     => 'WordPress',
        'drupal'        => 'Drupal',
        'joomla'        => 'Joomla',
        'piwik'         => 'Piwik',
        'discuz'        => 'Discuz!',
    
        # Tools
        'git'           => 'Git',
        'svn'           => 'SVN',
        'vim'           => 'VIM',
        'emacs'         => 'Emacs',
        'textmate'      => 'TextMate',
        'sublime'       => 'Sublime',
        'rubymine'      => 'RubyMine',
        'sequelpro'     => 'Sequel Pro',
        'virtualbox'    => 'VirtualBox',
        'safari'        => 'Safari',
        'chrome'        => 'Chrome',
        'ie'            => 'IE',
        'firefox'       => 'Firefox',
        'dash'          => 'Dash',
        'termal'        => 'Termal',
        'iterm'         => 'iTerm',
        'iterm2'        => 'iTerm2',
        'iwork'         => 'iWork',
        'itunes'        => 'iTunes',
        'iphoto'        => 'iPhoto',
        'ibook'         => 'iBook',
        'imessage'      => 'iMessage',
        'tweetbot'      => 'TweetBot',
        'sparrow'       => 'Sparrow',
        'photoshop'     => 'Photoshop',
        'office'        => 'Office',
        'word'          => 'Word',
        'excel'         => 'Excel',
        'powerpoint'    => 'PowerPoint',
    
        # Misc
        'app'           => 'App',
        'ios'           => 'iOS',
        'iphone'        => 'iPhone',
        'ipad'          => 'iPad',
        'android'       => 'Android',
        'osx'           => 'OS X',
        'mac'           => 'Mac',
        'imac'          => 'iMac',
        'macbookpro'    => 'MacBook Pro',
        'macbook'       => 'MacBook',
        'rmbp'          => 'rMBP',
        'wi-fi'         => 'Wi-Fi',
        'wifi'          => 'Wi-Fi',
        'vps'           => 'VPS',
        'vpn'           => 'VPN',
        'arm'           => 'ARM',
        'cpu'           => 'CPU',
        'pdf'           => 'PDF',
    );
